theme: jekyll-theme-minimal-0.2.0
title: Teng's Github Personal Website
description: This website demonstrates the personal life of Teng Zhang, Ph.D candidate near Lansing, MI. I am checking if the update is successful, to be honest...
logo: logo.jpg
#Or I can also add a logo from an image URL, as below
#logo: XXX
